### PR TITLE
Fix Baseband

### PR DESCRIPTION
**Pull request by aldi45ckr**
Original by AragaoAnderson

### CODE REVIEW

**Comment by aldi45ckr** [comment]
Why you don't merge it?

**Comment by xnickbrandtx** [comment]
It's not how you properly fix it. Furthermore the board name is not msm8916

**Comment by aldi45ckr** [comment]
http://s22.postimg.org/40b4qofm9/Screenshot_20160127_192110.png

**Comment by aldi45ckr** [comment]
Or you change to 
    char platform[PROP_VALUE_MAX];
    char modem_version[IMG_VER_BUF_LEN];
    int rc;

    UNUSED(msm_id);
    UNUSED(msm_ver);
    UNUSED(board_type);

    rc = property_get("ro.board.platform", platform);
    if (!rc || !ISMATCH(platform, ANDROID_TARGET))
        return;

**Comment by xnickbrandtx** [comment]
The real board name is S88047E1 or something else if you have the Redmi 2 Prime. There is a simpler fix coming in the next build. I don't want to argue with you or anything but you can check my repos to see the changes.

**Pull request closed without merging**
